[features]
seeds = false
[programs.localnet]
solana_verifier = "ETYYD1fm5fNoTe9HnHYbc9yf9oFZ2kbqEmBvbRwnAPzv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/piotr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
